---
version: 2
project_name: arkd

builds:
  - id: arkd-darwin-amd64
    main: ./scripts/ci-goreleaser/goreleaser.go
    binary: arkd
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - ./scripts/ci-goreleaser/.goreleaser_hook.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}

  - id: arkd-darwin-arm64
    main: ./scripts/ci-goreleaser/goreleaser.go
    binary: arkd
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - ./scripts/ci-goreleaser/.goreleaser_hook.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}

  - id: arkd-linux-amd64
    main: ./scripts/ci-goreleaser/goreleaser.go
    binary: arkd
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - ./scripts/ci-goreleaser/.goreleaser_hook.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}

  - id: arkd-linux-arm64
    main: ./scripts/ci-goreleaser/goreleaser.go
    binary: arkd
    goos:
      - linux
    goarch:
      - arm64
    hooks:
      post:
        - ./scripts/ci-goreleaser/.goreleaser_hook.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}

archives:
  - id: zipped
    builds:
      - arkd-linux-amd64
      - arkd-linux-arm64
      - arkd-darwin-amd64
      - arkd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - arkd-linux-amd64
      - arkd-linux-arm64
      - arkd-darwin-amd64
      - arkd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg
    stdin: "{{ .Env.GPG_PASSWORD }}"
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase-fd"
      - "0"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

# Docs: https://goreleaser.com/customization/release/
# Note: it will includes the .sig of the checksum file by default
release:
  github:
    owner: "{{ .Env.REPO_OWNER }}"
    name: "{{ .Env.REPO_NAME }}"
  replace_existing_draft: true
  header: |
    < DESCRIPTION OF RELEASE >

    ## Changelog

    See the full changelog [here](https://github.com/{{ .Env.REPO_OWNER }}/{{ .Env.REPO_NAME }}/blob/v{{ .Version }}/CHANGELOG.md)

    #### 🔨 Build from source

    If you prefer to build from source, you can use the following commands:

    ````bash
    git clone https://github.com/{{ .Env.REPO_OWNER }}/{{ .Env.REPO_NAME }}
    cd ArkConstellation && git checkout v{{ .Version }}
    make install
    ````

  name_template: "ArkConstellation v{{.Version}}"
  mode: replace
  draft: true

# Docs: https://goreleaser.com/customization/announce/
# We could automatically announce the release in
# - discord
# - slack
# - twitter
# - webhooks
# - telegram
# - reddit
#
# announce:
  # discord:
  #   enabled: true
  #   message_template: 'New {{.Tag}} is out!'
